### ISSUE TITLE
staging failure because setup.py needs to import a third-party module

### ISSUE THREAD

**Issue by aad** [cloudfoundry/python-buildpack#112]
### What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

```
cf curl /v2/info && cf version
{
   "name": "",
   "build": "",
   "support": "",
   "version": 0,
   "description": "",
   "authorization_endpoint": "https://xxx.com",
   "token_endpoint": "https://xxx.com",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "api_version": "2.102.0",
   "app_ssh_endpoint": "xxx.com:2222",
   "app_ssh_host_key_fingerprint": "2QtA7gdsTXaHV3wzJvA4nmO7VrKT5A4MvHCDiVbeISE",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://xxx.com:443",
   "routing_endpoint": "https://api.xxx.com/routing"
}
cf version 6.29.0+ff886fa93.2017-07-24
```

### What version of the buildpack you are using?
```Python Buildpack version 1_6_17```

### If you were attempting to accomplish a task, what was it you were attempting to do?

add below into requirements.txt and vendor all the packages required and push the app
```
cvxpy==0.4.11
numpy==1.11.3
ecos>=2 
```

### What did you expect to happen?
i want to have package `ecos>=2` installed successfully in the offline mode (vendoring).

It seems in the staging phase, `collecting` and `installing` are separated. Install will not start till  all collecting done.

If we can have some packages (in our case numpy which is already in the vendor directory) actually installed before other packages start collecting phase, that will resolve this case

### What was the actual behavior?
during staging phase, in ecos setup.py (https://github.com/embotech/ecos-python/blob/v2.0.5/setup.py#L10), it tried to `import numpy` and it got error as below. 
```
          Collecting ecos>=2 (from cvxpy==0.4.11->-r /tmp/contents421252386/deps/0/requirements.txt (line 7))
              Complete output from command python setup.py egg_info:
              Traceback (most recent call last):
                File "<string>", line 1, in <module>
                File "/tmp/pip-build-dsrdnz07/ecos/setup.py", line 10, in <module>
                  import numpy
              ModuleNotFoundError: No module named 'numpy'
              
```

###  more logs
```
  Downloaded app package (86.3M)
   -----> Python Buildpack version 1_6_17
   -----> Supplying Python
   -----> Installing python 3.6.5
          Copy [/tmp/buildpacks/12ee44bc5c27d5e7f5ff4de48c0e3be1/dependencies/60a1b51efe33258de8aa056377d349fc/python-3.6.5-linux-x64-81bdefa8.tgz]
   -----> Installing setuptools 39.2.0
          Copy [/tmp/buildpacks/12ee44bc5c27d5e7f5ff4de48c0e3be1/dependencies/ed067fe948b8b8b08082d1d8ccc44f7d/setuptools-39.2.0-f7cddbb5.zip]
   -----> Installing pip 9.0.3
          Copy [/tmp/buildpacks/12ee44bc5c27d5e7f5ff4de48c0e3be1/dependencies/237d732569d1efd5ca7ddafbef3d9a10/pip-9.0.3-7bf48f9a.tar.gz]
   -----> Installing pip-pop 0.1.1
          Copy [/tmp/buildpacks/12ee44bc5c27d5e7f5ff4de48c0e3be1/dependencies/ee6dcba05f17753b4c10c2ab872711d6/pip-pop-0.1.1-d410583a.tar.gz]
   -----> Running Pip Install
          Collecting aniso8601==1.2.1 (from -r /tmp/contents421252386/deps/0/requirements.txt (line 1))
          Collecting cvxpy==0.4.11 (from -r /tmp/contents421252386/deps/0/requirements.txt (line 7))
          Collecting linecache2==1.0.0 (from -r /tmp/contents421252386/deps/0/requirements.txt (line 18))
          ......
          ......
          Collecting MarkupSafe==1.0 (from -r /tmp/contents421252386/deps/0/requirements.txt (line 19))
          Collecting numpy==1.11.3 (from -r /tmp/contents421252386/deps/0/requirements.txt (line 20))
          Collecting pandas==0.23 (from -r /tmp/contents421252386/deps/0/requirements.txt (line 21))
          Collecting pip==10.0.1 (from -r /tmp/contents421252386/deps/0/requirements.txt (line 22))
          Collecting py==1.4.33 (from -r /tmp/contents421252386/deps/0/requirements.txt (line 23))
          Collecting pytest==3.1.0 (from -r /tmp/contents421252386/deps/0/requirements.txt (line 24))
          Collecting python-dateutil==2.6.0 (from -r /tmp/contents421252386/deps/0/requirements.txt (line 25))
          Collecting pytz==2017.2 (from -r /tmp/contents421252386/deps/0/requirements.txt (line 26))
          Collecting scipy==0.19.0 (from -r /tmp/contents421252386/deps/0/requirements.txt (line 27))
          Collecting setuptools==28.8.0 (from -r /tmp/contents421252386/deps/0/requirements.txt (line 28))
          Collecting six==1.10.0 (from -r /tmp/contents421252386/deps/0/requirements.txt (line 29))
          Collecting traceback2==1.4.0 (from -r /tmp/contents421252386/deps/0/requirements.txt (line 30))
          Collecting unittest2==1.1.0 (from -r /tmp/contents421252386/deps/0/requirements.txt (line 31))
          Collecting Werkzeug==0.12.1 (from -r /tmp/contents421252386/deps/0/requirements.txt (line 32))
          Collecting xlrd==1.0.0 (from -r /tmp/contents421252386/deps/0/requirements.txt (line 33))
          Collecting requests==2.18.1 (from -r /tmp/contents421252386/deps/0/requirements.txt (line 37))
          Collecting ecos>=2 (from cvxpy==0.4.11->-r /tmp/contents421252386/deps/0/requirements.txt (line 7))
              Complete output from command python setup.py egg_info:
              Traceback (most recent call last):
                File "<string>", line 1, in <module>
                File "/tmp/pip-build-dsrdnz07/ecos/setup.py", line 10, in <module>
                  import numpy
              ModuleNotFoundError: No module named 'numpy'
              
              ----------------------------------------
   [31m       Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dsrdnz07/ecos/[0m
          pip install has failed. You have a vendor directory, it must contain all of your dependencies.
          [31;1m**ERROR**[0m Could not install pip packages: Couldn't run pip: exit status 1
   [31mFailed to compile droplet: Failed to run all supply scripts: exit status 14[0m
   Exit status 223
   Stopping instance c56e0f8c-a886-410e-a3af-378d3b91ee63
   Destroying container
   Successfully destroyed container
Error staging application: App staging failed in the buildpack compile phase
[31;1mFAILED[0m
```

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by astrieanna** [comment]
@aad Why does collecting `ecos` require `numpy` to be installed? This seems surprising to me.

**Comment by astrieanna** [comment]
@aad ^^ do you know why `ecos` requires `numpy` for the collecting stage?

**Comment by aad** [comment]
I don't know the reason but it's here in the setup.py https://github.com/embotech/ecos-python/blob/v2.0.5/setup.py#L24

**Comment by sclevine** [comment]
It looks like the latest RCs of v2.0.7 use a build extension to install this:
https://github.com/embotech/ecos-python/blob/2.0.7rc2/setup.py#L50

@aad could you try with 2.0.7rc2 and let us know if it works?

**Comment by tylerphelan** [comment]
@aad Closing this out due to inactivity. Feel free to re-open if you continue having problems.
