### ISSUE TITLE
Buildpack stopped working after version bump to 1.6.19

### ISSUE THREAD

**Issue by artursmolarek** [cloudfoundry/python-buildpack#115]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

```
{
   "name": "pcfdev",
   "build": "4af54097fef22734d857410ddfb89ee979087911",
   "support": "pcfdev@pivotal.io",
   "version": 0,
   "description": "",
   "authorization_endpoint": "https://login.local.pcfdev.io",
   "token_endpoint": "https://uaa.local.pcfdev.io",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "api_version": "2.82.0",
   "app_ssh_endpoint": "ssh.local.pcfdev.io:2222",
   "app_ssh_host_key_fingerprint": "a6:d1:08:0b:b0:cb:9b:5f:c4:ba:44:2a:97:26:19:8a",
   "app_ssh_oauth_client": "ssh-proxy",
   "routing_endpoint": "https://api.local.pcfdev.io/routing",
   "doppler_logging_endpoint": "wss://doppler.local.pcfdev.io:443",
   "user": "13094f3b-c967-4902-824c-ef169e7ad0df"
}
cf version 6.37.0+a40009753.2018-05-25
```

What version of the buildpack you are using?

`1.6.19`

If you were attempting to accomplish a task, what was it you were attempting to do?

`I'm trying to push sidecar-python-demo (https://github.com/rhardt-pivotal/sidecar-python-demo) application.`

What did you expect to happen?

`Application should start.`

What was the actual behavior?

```
Creating container
Successfully created container
Downloading app package...
Downloaded app package (1.9K)
Staging...
ORIG_DIR=/tmp/buildpacks/ef41073c48d41e49c1e7a4fb9b05bef3/bin
=====> Downloading Buildpack: https://github.com/cloudfoundry/python-buildpack.git
=====> Detected Framework: python 1.6.19
about to run /tmp/buildpackfrnWo/bin/compile /tmp/app /tmp/cache
calling /tmp/buildpackfrnWo/bin/compile from /home/vcap
-----> Download go 1.9.1
-----> Running go build supply
-----> Python Buildpack version 1.6.19
-----> Supplying Python
-----> Installing python 2.7.15
       Download [https://buildpacks.cloudfoundry.org/dependencies/python/python-2.7.15-linux-x64-d8ee0ad8.tgz]
-----> Installing setuptools 39.2.0
       Download [https://buildpacks.cloudfoundry.org/dependencies/setuptools/setuptools-39.2.0-f7cddbb5.zip]
-----> Installing pip 9.0.3
       Download [https://buildpacks.cloudfoundry.org/dependencies/pip/pip-9.0.3-7bf48f9a.tar.gz]
-----> Installing pip-pop 0.1.1
       Download [https://buildpacks.cloudfoundry.org/dependencies/manual-binaries/pip-pop/pip-pop-0.1.1-d410583a.tar.gz]
-----> Running Pip Install
       Collecting Flask (from -r /tmp/app/.cloudfoundry/0/requirements.txt (line 1))
         Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)'),)': /packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl
         Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)'),)': /packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl
         Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)'),)': /packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl
         Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)'),)': /packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl
         Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)'),)': /packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl
       Exception:
       Traceback (most recent call last):
         File "/tmp/app/.cloudfoundry/0/python/lib/python2.7/site-packages/pip-9.0.3-py2.7.egg/pip/basecommand.py", line 215, in main
           status = self.run(options, args)
         File "/tmp/app/.cloudfoundry/0/python/lib/python2.7/site-packages/pip-9.0.3-py2.7.egg/pip/commands/install.py", line 324, in run
           requirement_set.prepare_files(finder)
         File "/tmp/app/.cloudfoundry/0/python/lib/python2.7/site-packages/pip-9.0.3-py2.7.egg/pip/req/req_set.py", line 380, in prepare_files
           ignore_dependencies=self.ignore_dependencies))
         File "/tmp/app/.cloudfoundry/0/python/lib/python2.7/site-packages/pip-9.0.3-py2.7.egg/pip/req/req_set.py", line 620, in _prepare_file
           session=self.session, hashes=hashes)
         File "/tmp/app/.cloudfoundry/0/python/lib/python2.7/site-packages/pip-9.0.3-py2.7.egg/pip/download.py", line 821, in unpack_url
           hashes=hashes
         File "/tmp/app/.cloudfoundry/0/python/lib/python2.7/site-packages/pip-9.0.3-py2.7.egg/pip/download.py", line 659, in unpack_http_url
           hashes)
         File "/tmp/app/.cloudfoundry/0/python/lib/python2.7/site-packages/pip-9.0.3-py2.7.egg/pip/download.py", line 853, in _download_http_url
           stream=True,
         File "/tmp/app/.cloudfoundry/0/python/lib/python2.7/site-packages/pip-9.0.3-py2.7.egg/pip/_vendor/requests/sessions.py", line 521, in get
           return self.request('GET', url, **kwargs)
         File "/tmp/app/.cloudfoundry/0/python/lib/python2.7/site-packages/pip-9.0.3-py2.7.egg/pip/download.py", line 386, in request
           return super(PipSession, self).request(method, url, *args, **kwargs)
         File "/tmp/app/.cloudfoundry/0/python/lib/python2.7/site-packages/pip-9.0.3-py2.7.egg/pip/_vendor/requests/sessions.py", line 508, in request
           resp = self.send(prep, **send_kwargs)
         File "/tmp/app/.cloudfoundry/0/python/lib/python2.7/site-packages/pip-9.0.3-py2.7.egg/pip/_vendor/requests/sessions.py", line 618, in send
           r = adapter.send(request, **kwargs)
         File "/tmp/app/.cloudfoundry/0/python/lib/python2.7/site-packages/pip-9.0.3-py2.7.egg/pip/_vendor/cachecontrol/adapter.py", line 47, in send
           resp = super(CacheControlAdapter, self).send(request, **kw)
         File "/tmp/app/.cloudfoundry/0/python/lib/python2.7/site-packages/pip-9.0.3-py2.7.egg/pip/_vendor/requests/adapters.py", line 506, in send
           raise SSLError(e, request=request)
       SSLError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)'),))
       You are using pip version 9.0.3, however version 10.0.1 is available.
       You should consider upgrading via the 'pip install --upgrade pip' command.
       **ERROR** Could not install pip packages: Couldn't run pip: exit status 2
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223
Destroying container
Successfully destroyed container

FAILED
Error restarting application: BuildpackCompileFailed
```

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by astrieanna** [comment]
Glad you got it working! :)
