### ISSUE TITLE
Data generated by pre_compile in /app is cleaned up

### ISSUE THREAD

**Issue by sergeybk** [cloudfoundry/python-buildpack#124]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

```
{
   "name": "",
   "build": "",
   "support": "...",
   "version": 0,
   "description": "...",
   "authorization_endpoint": "...",
   "token_endpoint": "...",
   "min_cli_version": "6.0.0",
   "min_recommended_cli_version": "6.10.0",
   "app_ssh_endpoint": "...",
   "app_ssh_host_key_fingerprint": "...",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "...",
   "api_version": "2.126.0",
   "osbapi_version": "2.14",
   "routing_endpoint": "..."
}
cf version 6.29.0+ff886fa.2017-07-24
```

What version of the buildpack you are using?

v1.6.21

If you were attempting to accomplish a task, what was it you were attempting to do?

I'm using _bin/pre_compile_ script to download, build, and install an unmanaged library used by one of Python packages (`couchbase==2.0.9`):

```
#!/usr/bin/env bash

_LIBCOUCHBASE_VER=2.10.2
_PROJECT_ROOT=/app

# Build and install Couchbase C SDK (core library only).
# Couchbase make code runs some Git commands, so requires making a clone.
git clone --depth 1 --branch $_LIBCOUCHBASE_VER \
    https://github.com/couchbase/libcouchbase.git /tmp/libcouchbase_$$
cd /tmp/libcouchbase_$$
./configure.pl \
    --prefix $_PROJECT_ROOT \
    --disable-tools \
    --disable-tests \
    --disable-plugins \
    --disable-couchbasemock
make
make install
```

What did you expect to happen?

`make install` deploys the binaries into the _/app_ folder (e.g. _/app/lib_, _/app/share_, _/app/include_), and the application can use them in runtime. Here is how the _manifest.yml_ looks like:
```
buildpack: https://github.com/cloudfoundry/python-buildpack.git#v1.6.21
stack: cflinuxfs3
env:
  C_INCLUDE_PATH: /app/include
  LIBRARY_PATH: /app/lib
  LD_LIBRARY_PATH: /app/lib
```

What was the actual behavior?

After `cf push` command completes, all the binaries generated by `make install` are deleted, and the application crashes due to missing dependencies.
This was not the case with buildpack v1.5.13, but since my organization moves to cflinuxfs3 I have to upgrade to 1.6.x

The workaround I found working: add _bin/post_compile_ script to explicitly copy the contents of the _/app_ folder into ${PYTHONPATH}, which is preserved by the buildpack:
```
#!/usr/bin/env bash

cp -r /app/* ${PYTHONPATH}
ls -l ${PYTHONPATH} > /dev/null
```

I'm not particularly proud of this implementation, so appreciate a better solution. Also, notice the non-functional second line: if I comment it out, the workaround stops working.

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by kardolus** [comment]
In the staging container `LD_LIBRARY_PATH=/app/lib`. In the launch container `LD_LIBRARY_PATH=/home/vcap/deps/0/lib:/app/lib`. The /app folder does not carry over from the staging container to the launch container. Interesting work around though; moving everything from the app folder to the PYTHONPATH in the post_compile hook. When post_compile runs in the staging container, the PYTHONPATH is set to `/tmp/contents<some_guid>/deps/0`. This folder does carry over and is available in the launch container as `/home/vcap/deps/0/`.

I think we could write a better solution on the buildpacks side. If the root folder of deps/0 is known during pre_compile then I don’t think we need a post_compile fix (?). I’m fairly new on the team though. @sclevine what do you think?

**Comment by sclevine** [comment]
`/app` has never pointed to the app dir during staging. Instead of copying the dependencies to `/app`, you can use the current working directory of the `pre_compile` or `post_compile` script.

**Comment by djoyahoy** [comment]
Hi @sergeybk, I was able to get this working using your pre_compile script and manifest.yml with minor changes:
```
#!/usr/bin/env bash

_LIBCOUCHBASE_VER=2.10.2
_PROJECT_ROOT=${PWD}

# Build and install Couchbase C SDK (core library only).
# Couchbase make code runs some Git commands, so requires making a clone.
git clone --depth 1 --branch $_LIBCOUCHBASE_VER \
    https://github.com/couchbase/libcouchbase.git /tmp/libcouchbase_$$
cd /tmp/libcouchbase_$$
./configure.pl \
    --prefix $_PROJECT_ROOT \
    --disable-tools \
    --disable-tests \
    --disable-plugins \
    --disable-couchbasemock
make
make install
```
and
```
buildpack: https://github.com/cloudfoundry/python-buildpack.git#v1.6.21
stack: cflinuxfs3
env:
  C_INCLUDE_PATH: /tmp/app/include
  LIBRARY_PATH: /tmp/app/lib
  LD_LIBRARY_PATH: /tmp/app/lib
```

Keep in mind that the env set by manifest.yml is "sticky". It will persist between pushes of your application. Try deleting your app with `cf delete <app_name>` and then pushing the application again.

It may also be worth ditching the pre_compile script and attempting to use the apt-buildpack to supply libcouchbase https://github.com/cloudfoundry/apt-buildpack

**Comment by sergeybk** [comment]
The application indeed starts, unless you actually try using couchbase library :)
Once you do, the following pops up:
```
[APP/PROC/WEB/0] ERR [2018-12-16 05:56:38 +0000] [8] [INFO] Starting gunicorn 19.6.0
[APP/PROC/WEB/0] ERR [2018-12-16 05:56:38 +0000] [8] [INFO] Listening at: http://0.0.0.0:8080 (8)
[APP/PROC/WEB/0] ERR [2018-12-16 05:56:38 +0000] [8] [INFO] Using worker: sync
[APP/PROC/WEB/0] ERR [2018-12-16 05:56:38 +0000] [61] [INFO] Booting worker with pid: 61
[APP/PROC/WEB/0] ERR [2018-12-16 05:56:38 +0000] [61] [ERROR] Exception in worker process
[APP/PROC/WEB/0] ERR Traceback (most recent call last):
[APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
[APP/PROC/WEB/0] ERR     worker.init_process()
[APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
[APP/PROC/WEB/0] ERR     self.load_wsgi()
[APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
[APP/PROC/WEB/0] ERR     self.wsgi = self.app.wsgi()
[APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
[APP/PROC/WEB/0] ERR     self.callable = self.load()
[APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
[APP/PROC/WEB/0] ERR     return self.load_wsgiapp()
[APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
[APP/PROC/WEB/0] ERR     return util.import_app(self.app_uri)
[APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
[APP/PROC/WEB/0] ERR     __import__(module)
[APP/PROC/WEB/0] ERR   File "/home/vcap/app/run.py", line 6, in <module>
[APP/PROC/WEB/0] ERR     from couchbase.bucket import Bucket
[APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/couchbase/__init__.py", line 28, in <module>
[APP/PROC/WEB/0] ERR     from couchbase.user_constants import *
[APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/couchbase/user_constants.py", line 21, in <module>
[APP/PROC/WEB/0] ERR     import couchbase._bootstrap
[APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/couchbase/_bootstrap.py", line 34, in <module>
[APP/PROC/WEB/0] ERR     import couchbase.exceptions as E
[APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/couchbase/exceptions.py", line 18, in <module>
[APP/PROC/WEB/0] ERR     import couchbase._libcouchbase as C
[APP/PROC/WEB/0] ERR ImportError: libcouchbase.so.2: cannot open shared object file: No such file or directory
[APP/PROC/WEB/0] ERR [2018-12-16 05:56:38 +0000] [61] [INFO] Worker exiting (pid: 61)
[APP/PROC/WEB/0] ERR [2018-12-16 05:56:38 +0000] [8] [INFO] Shutting down: Master
[APP/PROC/WEB/0] ERR [2018-12-16 05:56:38 +0000] [8] [INFO] Reason: Worker failed to boot.
```

To reproduce, please add the following code to your main method:
```python
from couchbase.bucket import Bucket
bucket = Bucket('connection_string', password='password')
```

**Comment by djoyahoy** [comment]
Oh no! Sorry @sergeybk. Try adding the following dir and file to your apps root, `.profile.d/setup_ld_path.sh` with the contents:
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/lib
```

**Comment by djoyahoy** [comment]
@sergeybk I'm glad to hear that this worked for you. I agree, this is a silly workaround. @sclevine is there something we can do here to make this experience less kludgy?
