### ISSUE TITLE
Getting error when installing packages with conda

### ISSUE THREAD

**Issue by ronert** [cloudfoundry/python-buildpack#42]
What version of Cloud Foundry are you using?

PCF 1.7

What version of the buildpack you are using?

Tried GitHub master and develop branch

If you were attempting to accomplish a task, what was it you were attempting to do?

Try to run the app I am currently working on (https://github.com/ronert/cf-predict)

What did you expect to happen?

I expected the buildpack to install all my dependencies specified in the environment.yml file.

What was the actual behavior?

PCF errored with 

````
2016-06-20T15:57:19.40+0200 [STG/0]      OUT The following packages will be UPDATED:
2016-06-20T15:57:20.57+0200 [STG/0]      OUT Fetching package metadata .......
2016-06-20T15:57:20.89+0200 [STG/0]      OUT Solving package specifications: ..........
2016-06-20T15:57:21.83+0200 [STG/0]      OUT     package                    |            build
2016-06-20T15:57:21.83+0200 [STG/0]      OUT     pip-8.1.2                  |           py35_0         1.6 MB
2016-06-20T15:57:21.83+0200 [STG/0]      OUT Package plan for installation in environment /tmp/app/.conda:
2016-06-20T15:57:21.83+0200 [STG/0]      OUT The following packages will be downloaded:
2016-06-20T15:57:21.83+0200 [STG/0]      OUT     ---------------------------|-----------------
2016-06-20T15:57:21.83+0200 [STG/0]      OUT The following packages will be UPDATED:
2016-06-20T15:57:21.83+0200 [STG/0]      OUT     pip: 8.1.1-py35_1 --> 8.1.2-py35_0
2016-06-20T15:57:21.89+0200 [STG/0]      OUT -----> Installing conda environment from environment.yml...
2016-06-20T15:57:23.16+0200 [STG/0]      OUT Fetching package metadata .......
2016-06-20T15:57:24.22+0200 [STG/0]      OUT Solving package specifications: ..........
2016-06-20T15:58:07.31+0200 [STG/0]      OUT An unexpected error has occurred, please consider sending the
2016-06-20T15:58:07.31+0200 [STG/0]      OUT     https://github.com/conda/conda/issues
2016-06-20T15:58:07.31+0200 [STG/0]      OUT Include the output of the command 'conda info' in your report.
2016-06-20T15:58:07.31+0200 [STG/0]      ERR Traceback (most recent call last):
2016-06-20T15:58:07.31+0200 [STG/0]      ERR     sys.exit(conda_env.cli.main.main())
2016-06-20T15:58:07.31+0200 [STG/0]      ERR   File "/tmp/app/.conda/lib/python3.5/site-packages/conda_env/cli/main.py", line 68, in main
2016-06-20T15:58:07.31+0200 [STG/0]      ERR     return args_func(args, parser)
2016-06-20T15:58:07.31+0200 [STG/0]      ERR   File "/tmp/app/.conda/lib/python3.5/site-packages/conda/cli/main.py", line 127, in args_func
2016-06-20T15:58:07.31+0200 [STG/0]      ERR     args.func(args, p)
2016-06-20T15:58:07.31+0200 [STG/0]      ERR   File "/tmp/app/.conda/lib/python3.5/site-packages/conda_env/cli/main_update.py", line 118, in execute
2016-06-20T15:58:07.31+0200 [STG/0]      ERR TypeError: install() got an unexpected keyword argument 'prune'
```
Ian Huston's [conda buildpack](https://github.com/ihuston/python-conda-buildpack) works fine with the same code. Maybe some miniconda behaviour changed?

**Comment by ronert** [comment]
I've also attached a log of what happens with the old conda buildpack vs. the develop branch of this Python buildpack.

[logs.zip](https://github.com/cloudfoundry/python-buildpack/files/323651/logs.zip)

**Comment by parente** [comment]
`$CONDA_BIN/conda update --yes --quiet conda-env` needs to be added to the buildpack to account for https://github.com/conda/conda/issues/2771

**Comment by parente** [comment]
Alternatively, conda 4.1 will contain a fix so that conda-env is updated automatically when `conda update conda` is used.

**Comment by Dannyzen** [comment]
@parente thanks for helping out here. @ronert I've made the change to a test buildpack on the develop branch of [my fork](https://github.com/Dannyzen/python-buildpack/tree/develop) which fixes this issue and successfully stages and launches cf-predict. Please give it a try and let us know if it works for you as well.

**Comment by ronert** [comment]
That works! Thanks @parente and @Dannyzen for the quick fix.

**Comment by RochesterinNYC** [comment]
@ronert This should be fixed in the latest version of the python buildpack (`1.5.7`). Thanks for the issue.
