### ISSUE TITLE
App with scikit-learn error: ERR ImportError: libgfortran.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by crawles** [cloudfoundry/python-buildpack#50]
What version of Cloud Foundry are you using?
API endpoint: https://api.local2.pcfdev.io (API version: 2.54.0)

What version of the buildpack you are using?
https://github.com/cloudfoundry/python-buildpack

If you were attempting to accomplish a task, what was it you were attempting to do?
Trying to push [this app](https://github.com/crawles/cf-heroku-anaconda-flask-example/tree/68d77fef5a08aec2653959062958c9aea67d02e9)

What did you expect to happen?
It to work

What was the actual behavior?

2016-08-31T10:35:55.02-0400 [API/0]      OUT App instance exited with guid 0caf2a47-245a-4a54-ad3b-e185081c2699 payload: {"instance"=>"bda29ec8-0ea7-443d-50c4-0a0a8ab9b77f", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* 2 error(s) occurred:\n\n* Exited with status 1\n* cancelled\n* cancelled", "crash_count"=>5, "crash_timestamp"=>1472654154980440286, "version"=>"334ec32f-bd9e-419e-ac7f-183af0a659e0"}

2016-08-31T10:35:54.90-0400 [APP/0]      ERR /home/vcap/app/.conda/envs/dep_env/lib/python3.5/site-packages/sklearn/utils/fixes.py:64: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
2016-08-31T10:35:54.90-0400 [APP/0]      ERR   if 'order' in inspect.getargspec(np.copy)[0]:
2016-08-31T10:35:54.90-0400 [APP/0]      ERR Traceback (most recent call last):
2016-08-31T10:35:54.90-0400 [APP/0]      ERR   File "app.py", line 7, in <module>
2016-08-31T10:35:54.90-0400 [APP/0]      ERR     from sklearn.linear_model import LogisticRegression
2016-08-31T10:35:54.90-0400 [APP/0]      ERR   File "/home/vcap/app/.conda/envs/dep_env/lib/python3.5/site-packages/sklearn/linear_model/__init__.py", line 15, in <module>
2016-08-31T10:35:54.90-0400 [APP/0]      ERR     from .least_angle import (Lars, LassoLars, lars_path, LarsCV, LassoLarsCV,
2016-08-31T10:35:54.90-0400 [APP/0]      ERR   File "/home/vcap/app/.conda/envs/dep_env/lib/python3.5/site-packages/sklearn/linear_model/least_angle.py", line 24, in <module>
2016-08-31T10:35:54.90-0400 [APP/0]      ERR     from ..utils import arrayfuncs, as_float_array, check_X_y
2016-08-31T10:35:54.90-0400 [APP/0]      ERR ImportError: libgfortran.so.1: cannot open shared object file: No such file or directory

**Something to note**: It's looking for python 3 even though I specified a Python2 app. FYI: I've seen this happen in the past.

Please confirm where necessary:
* [x ] I have included a log output 
* [x ] My log includes an error message 
* [x ] I have included steps for reproduction

**Comment by crawles** [comment]
Also, I ran cf delete before I pushed this app - i.e, I pushed a new instance of this app

**Comment by crawles** [comment]
Tried changing environment.yml to newest versions:
```
name: pydata_dependencies
dependencies:
- flask=0.11.1
- numpy=1.11
- pandas=0.18.1
- scipy=0.17.1
- scikit-learn=0.17.1
```

And now getting:

```
2016-08-31T11:02:01.40-0400 [APP/0]      ERR   File "app.py", line 7, in <module>
2016-08-31T11:02:01.40-0400 [APP/0]      ERR     from sklearn.linear_model import LogisticRegression
2016-08-31T11:02:01.40-0400 [APP/0]      ERR   File "/home/vcap/app/.conda/envs/dep_env/lib/python3.5/site-packages/sklearn/linear_model/__init__.py", line 12, in <module>
2016-08-31T11:02:01.40-0400 [APP/0]      ERR     from .base import LinearRegression
2016-08-31T11:02:01.40-0400 [APP/0]      ERR   File "/home/vcap/app/.conda/envs/dep_env/lib/python3.5/site-packages/sklearn/linear_model/base.py", line 32, in <module>
2016-08-31T11:02:01.40-0400 [APP/0]      ERR     from ..utils.sparsefuncs import mean_variance_axis, inplace_column_scale
2016-08-31T11:02:01.40-0400 [APP/0]      ERR   File "/home/vcap/app/.conda/envs/dep_env/lib/python3.5/site-packages/sklearn/utils/sparsefuncs.py", line 10, in <module>
2016-08-31T11:02:01.40-0400 [APP/0]      ERR     from .sparsefuncs_fast import (
2016-08-31T11:02:01.40-0400 [APP/0]      ERR ImportError: cannot import name 'incr_mean_variance_axis0'
```

**Comment by jchesterpivotal** [comment]
Hi @crawles,

My first instinct on googling was that your numpy/scipy might be pinned to old versions, but that appears not to be the case.

Looks as though adding `libgfortran` to your list of Conda dependencies is [the accepted fix](https://github.com/travis-ci/travis-ci/issues/4816#issuecomment-145512003). Can you advise if that works for you?

**Comment by crawles** [comment]
Hi @jchesterpivotal - thanks for your help. 

It appears to be working now with no changes to Conda dependencies or any other changes. After coming back - as a first pass - I tried again after restarting PCF Dev (where I'm running PCF) and it is working now. Not sure why it's working now.

**Comment by jchesterpivotal** [comment]
... weird.

Do you want to close? We can reopen if it reoccurs.

**Comment by crawles** [comment]
Yes, sounds good

**Comment by sesmith177** [comment]
Thanks, closing for now
