### ISSUE TITLE
CF not recognizing package even though it's in environment.yml

### ISSUE THREAD

**Issue by crawles** [cloudfoundry/python-buildpack#61]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

   "name": "",
   "build": "",
   "support": "https://support.pivotal.io",
   "version": 0,
   "description": "",
   "authorization_endpoint": "https://login.run.pez.pivotal.io",
   "token_endpoint": "https://uaa.run.pez.pivotal.io",
   "min_cli_version": "6.7.0",
   "min_recommended_cli_version": "6.11.2",
   "api_version": "2.65.0",
   "app_ssh_endpoint": "ssh.run.pez.pivotal.io:2222",
   "app_ssh_host_key_fingerprint": "9d:fb:3c:63:b5:fa:be:c2:50:cc:a6:a7:31:f4:a8:4b",
   "app_ssh_oauth_client": "ssh-proxy",
   "routing_endpoint": "https://api.run.pez.pivotal.io/routing",
   "logging_endpoint": "wss://loggregator.run.pez.pivotal.io:443",
   "doppler_logging_endpoint": "wss://doppler.run.pez.pivotal.io:443",
   "user": "9bfb61cc-7859-445b-af24-2d5c49dafe75"
}

What version of the buildpack you are using?
newest from github

If you were attempting to accomplish a task, what was it you were attempting to do?
push an app

What did you expect to happen?
it to work

What was the actual behavior?
It says it can't import flask even though I put it in my environment.yml

2017-01-20T11:24:49.96-0500 [APP/PROC/WEB/0]ERR     from flask import Flask, request, jsonify
2017-01-20T11:24:49.96-0500 [APP/PROC/WEB/0]ERR ImportError: No module named flask

I think install is stuck in the cache or something but it can't find it because at one point it says:
2017-01-20T11:22:39.45-0500 [STG/0]      OUT Requirement already satisfied: flask in /tmp/app/.conda/envs/dep_env/lib/python2.7/site-packages

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [ ] I have included steps for reproduction

2017-01-20T11:21:59.45-0500 [API/2]      OUT Updated app with guid 008999e4-ea4c-495b-806f-5cf2ff3b7159 ({"name"=>"compute-tweet-stats", "command"=>"PRIVATE DATA HIDDEN", "instances"=>1, "memory"=>256, "disk_quota"=>1024, "buildpack"=>"https://github.com/cloudfoundry/python-buildpack.git", "environment_json"=>"PRIVATE DATA HIDDEN"})
2017-01-20T11:22:08.14-0500 [API/3]      OUT Updated app with guid 008999e4-ea4c-495b-806f-5cf2ff3b7159 ({"state"=>"STOPPED"})
2017-01-20T11:22:09.58-0500 [API/6]      OUT Updated app with guid 008999e4-ea4c-495b-806f-5cf2ff3b7159 ({"state"=>"STARTED"})
2017-01-20T11:22:09.67-0500 [STG/0]      OUT Creating container
2017-01-20T11:22:10.02-0500 [STG/0]      OUT Successfully created container
2017-01-20T11:22:10.02-0500 [STG/0]      OUT Downloading app package...
2017-01-20T11:22:10.05-0500 [STG/0]      OUT Downloaded app package (3.6K)
2017-01-20T11:22:10.05-0500 [STG/0]      OUT Downloading build artifacts cache...
2017-01-20T11:22:20.14-0500 [STG/0]      OUT Downloaded build artifacts cache (252.3M)
2017-01-20T11:22:20.14-0500 [STG/0]      OUT Staging...
2017-01-20T11:22:27.08-0500 [STG/0]      OUT ----------------- USING CONDA BUILDPACK -----------------
2017-01-20T11:22:27.08-0500 [STG/0]      OUT -----> Starting compile step...
2017-01-20T11:22:27.09-0500 [STG/0]      OUT -----> Preparing Python Environment...
2017-01-20T11:22:27.10-0500 [STG/0]      OUT PREFIX=/tmp/app/.conda
2017-01-20T11:22:27.33-0500 [STG/0]      OUT installing: python-2.7.12-1 ...
2017-01-20T11:22:29.40-0500 [STG/0]      OUT installing: conda-env-2.6.0-0 ...
2017-01-20T11:22:29.41-0500 [STG/0]      OUT installing: enum34-1.1.6-py27_0 ...
2017-01-20T11:22:29.42-0500 [STG/0]      OUT installing: openssl-1.0.2j-0 ...
2017-01-20T11:22:29.90-0500 [STG/0]      OUT installing: pycosat-0.6.1-py27_1 ...
2017-01-20T11:22:29.95-0500 [STG/0]      OUT installing: readline-6.2-2 ...
2017-01-20T11:22:30.04-0500 [STG/0]      OUT installing: requests-2.11.1-py27_0 ...
2017-01-20T11:22:30.14-0500 [STG/0]      OUT installing: ruamel_yaml-0.11.14-py27_0 ...
2017-01-20T11:22:30.20-0500 [STG/0]      OUT installing: sqlite-3.13.0-0 ...
2017-01-20T11:22:30.79-0500 [STG/0]      OUT installing: tk-8.5.18-0 ...
2017-01-20T11:22:31.09-0500 [STG/0]      OUT installing: yaml-0.1.6-0 ...
2017-01-20T11:22:31.13-0500 [STG/0]      OUT installing: zlib-1.2.8-3 ...
2017-01-20T11:22:31.16-0500 [STG/0]      OUT installing: conda-4.2.12-py27_0 ...
2017-01-20T11:22:31.25-0500 [STG/0]      OUT installing: pycrypto-2.6.1-py27_4 ...
2017-01-20T11:22:31.36-0500 [STG/0]      OUT installing: pip-8.1.2-py27_0 ...
2017-01-20T11:22:31.68-0500 [STG/0]      OUT installing: wheel-0.29.0-py27_0 ...
2017-01-20T11:22:31.71-0500 [STG/0]      OUT installing: setuptools-27.2.0-py27_0 ...
2017-01-20T11:22:31.77-0500 [STG/0]      ERR Python 2.7.12 :: Continuum Analytics, Inc.
2017-01-20T11:22:31.77-0500 [STG/0]      OUT creating default environment...
2017-01-20T11:22:32.38-0500 [STG/0]      OUT installation finished.
2017-01-20T11:22:32.38-0500 [STG/0]      OUT -----> Using dependency cache at /tmp/cache/envs
2017-01-20T11:22:33.54-0500 [STG/0]      OUT -----> Installing Dependencies...
2017-01-20T11:22:33.54-0500 [STG/0]      OUT -----> Installing conda environment from environment.yml...
2017-01-20T11:22:35.96-0500 [STG/0]      OUT Fetching package metadata .......
2017-01-20T11:22:36.99-0500 [STG/0]      OUT Solving package specifications: ..........
2017-01-20T11:22:39.45-0500 [STG/0]      OUT Requirement already satisfied: flask in /tmp/app/.conda/envs/dep_env/lib/python2.7/site-packages
2017-01-20T11:22:39.47-0500 [STG/0]      OUT Requirement already satisfied: gunicorn in /tmp/app/.conda/envs/dep_env/lib/python2.7/site-packages
2017-01-20T11:22:39.47-0500 [STG/0]      OUT Requirement already satisfied: redis in /tmp/app/.conda/envs/dep_env/lib/python2.7/site-packages
2017-01-20T11:22:39.48-0500 [STG/0]      OUT Requirement already satisfied: Werkzeug>=0.7 in /tmp/app/.conda/envs/dep_env/lib/python2.7/site-packages (from flask)
2017-01-20T11:22:39.49-0500 [STG/0]      OUT Requirement already satisfied: Jinja2>=2.4 in /tmp/app/.conda/envs/dep_env/lib/python2.7/site-packages (from flask)
2017-01-20T11:22:39.50-0500 [STG/0]      OUT Requirement already satisfied: itsdangerous>=0.21 in /tmp/app/.conda/envs/dep_env/lib/python2.7/site-packages (from flask)
2017-01-20T11:22:39.50-0500 [STG/0]      OUT Requirement already satisfied: click>=2.0 in /tmp/app/.conda/envs/dep_env/lib/python2.7/site-packages (from flask)
2017-01-20T11:22:39.50-0500 [STG/0]      OUT Requirement already satisfied: MarkupSafe in /tmp/app/.conda/envs/dep_env/lib/python2.7/site-packages (from Jinja2>=2.4->flask)
2017-01-20T11:22:39.54-0500 [STG/0]      OUT #
2017-01-20T11:22:39.54-0500 [STG/0]      OUT # To activate this environment, use:
2017-01-20T11:22:39.54-0500 [STG/0]      OUT # > source activate dep_env
2017-01-20T11:22:39.54-0500 [STG/0]      OUT #
2017-01-20T11:22:39.54-0500 [STG/0]      OUT # To deactivate this environment, use:
2017-01-20T11:22:39.54-0500 [STG/0]      OUT # > source deactivate dep_env
2017-01-20T11:22:39.54-0500 [STG/0]      OUT #
2017-01-20T11:22:39.98-0500 [STG/0]      OUT Cache location:
2017-01-20T11:22:39.98-0500 [STG/0]      OUT There are no tarballs to remove
2017-01-20T11:22:39.98-0500 [STG/0]      OUT Cache location: /tmp/app/.conda/pkgs
2017-01-20T11:22:39.98-0500 [STG/0]      OUT Will remove the following packages:
2017-01-20T11:22:39.98-0500 [STG/0]      OUT /tmp/app/.conda/pkgs
2017-01-20T11:22:39.98-0500 [STG/0]      OUT --------------------
2017-01-20T11:22:39.98-0500 [STG/0]      OUT setuptools-27.2.0-py27_0                     529 KB
2017-01-20T11:22:39.98-0500 [STG/0]      OUT pycosat-0.6.1-py27_1                         600 KB
2017-01-20T11:22:39.98-0500 [STG/0]      OUT conda-env-2.6.0-0                             454 B
2017-01-20T11:22:39.98-0500 [STG/0]      OUT ---------------------------------------------------
2017-01-20T11:22:39.98-0500 [STG/0]      OUT Total:                                       1.1 MB
2017-01-20T11:22:39.98-0500 [STG/0]      OUT Proceed ([y]/n)?
2017-01-20T11:22:39.98-0500 [STG/0]      OUT removing setuptools-27.2.0-py27_0
2017-01-20T11:22:39.98-0500 [STG/0]      OUT removing pycosat-0.6.1-py27_1
2017-01-20T11:22:39.98-0500 [STG/0]      OUT removing conda-env-2.6.0-0
2017-01-20T11:22:40.00-0500 [STG/0]      OUT -----> Caching dependencies to /tmp/cache/envs
2017-01-20T11:22:42.40-0500 [STG/0]      OUT -----> Fixing paths...
2017-01-20T11:22:43.26-0500 [STG/0]      OUT -----> Finished compile step
2017-01-20T11:22:44.06-0500 [STG/0]      ERR No start command specified by buildpack or via Procfile.
2017-01-20T11:22:44.06-0500 [STG/0]      ERR App will not start unless a command is provided at runtime.
2017-01-20T11:24:01.31-0500 [STG/0]      OUT Exit status 0
2017-01-20T11:24:01.31-0500 [STG/0]      OUT Staging complete
2017-01-20T11:24:01.31-0500 [STG/0]      OUT Uploading droplet, build artifacts cache...
2017-01-20T11:24:01.31-0500 [STG/0]      OUT Uploading build artifacts cache...
2017-01-20T11:24:01.31-0500 [STG/0]      OUT Uploading droplet...
2017-01-20T11:24:07.53-0500 [STG/0]      OUT Uploaded build artifacts cache (252.3M)
2017-01-20T11:24:16.44-0500 [STG/0]      OUT Uploaded droplet (216.5M)
2017-01-20T11:24:16.48-0500 [STG/0]      OUT Uploading complete
2017-01-20T11:24:16.50-0500 [STG/0]      OUT Destroying container
2017-01-20T11:24:17.14-0500 [CELL/0]     OUT Creating container
2017-01-20T11:24:17.41-0500 [STG/0]      OUT Successfully destroyed container
2017-01-20T11:24:17.61-0500 [CELL/0]     OUT Successfully created container
2017-01-20T11:24:33.71-0500 [CELL/0]     OUT Starting health monitoring of container
2017-01-20T11:24:35.51-0500 [APP/PROC/WEB/0]ERR [2017-01-20 16:24:35 +0000] [14] [INFO] Starting gunicorn 19.6.0
2017-01-20T11:24:35.51-0500 [APP/PROC/WEB/0]ERR [2017-01-20 16:24:35 +0000] [14] [INFO] Listening at: http://0.0.0.0:8080 (14)
2017-01-20T11:24:35.51-0500 [APP/PROC/WEB/0]ERR [2017-01-20 16:24:35 +0000] [14] [INFO] Using worker: sync
2017-01-20T11:24:35.51-0500 [APP/PROC/WEB/0]ERR [2017-01-20 16:24:35 +0000] [64] [INFO] Booting worker with pid: 64
2017-01-20T11:24:35.53-0500 [APP/PROC/WEB/0]ERR [2017-01-20 16:24:35 +0000] [64] [ERROR] Exception in worker process
2017-01-20T11:24:35.53-0500 [APP/PROC/WEB/0]ERR Traceback (most recent call last):
2017-01-20T11:24:35.53-0500 [APP/PROC/WEB/0]ERR   File "/home/vcap/app/.conda/envs/dep_env/lib/python2.7/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
2017-01-20T11:24:35.53-0500 [APP/PROC/WEB/0]ERR     worker.init_process()
2017-01-20T11:24:35.53-0500 [APP/PROC/WEB/0]ERR   File "/home/vcap/app/.conda/envs/dep_env/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
2017-01-20T11:24:35.53-0500 [APP/PROC/WEB/0]ERR     self.load_wsgi()
2017-01-20T11:24:35.53-0500 [APP/PROC/WEB/0]ERR   File "/home/vcap/app/.conda/envs/dep_env/lib/python2.7/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
2017-01-20T11:24:35.53-0500 [APP/PROC/WEB/0]ERR     self.wsgi = self.app.wsgi()
2017-01-20T11:24:35.53-0500 [APP/PROC/WEB/0]ERR   File "/home/vcap/app/.conda/envs/dep_env/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2017-01-20T11:24:35.53-0500 [APP/PROC/WEB/0]ERR     self.callable = self.load()
2017-01-20T11:24:35.53-0500 [APP/PROC/WEB/0]ERR   File "/home/vcap/app/.conda/envs/dep_env/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2017-01-20T11:24:35.53-0500 [APP/PROC/WEB/0]ERR     return self.load_wsgiapp()
2017-01-20T11:24:35.53-0500 [APP/PROC/WEB/0]ERR   File "/home/vcap/app/.conda/envs/dep_env/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2017-01-20T11:24:35.53-0500 [APP/PROC/WEB/0]ERR     return util.import_app(self.app_uri)
2017-01-20T11:24:35.53-0500 [APP/PROC/WEB/0]ERR   File "/home/vcap/app/.conda/envs/dep_env/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
2017-01-20T11:24:35.53-0500 [APP/PROC/WEB/0]ERR     __import__(module)
2017-01-20T11:24:35.53-0500 [APP/PROC/WEB/0]ERR   File "/home/vcap/app/tweet_rate.py", line 5, in <module>
2017-01-20T11:24:35.53-0500 [APP/PROC/WEB/0]ERR     from flask import Flask, request, jsonify
2017-01-20T11:24:35.53-0500 [APP/PROC/WEB/0]ERR ImportError: No module named flask
2017-01-20T11:24:35.53-0500 [APP/PROC/WEB/0]ERR [2017-01-20 16:24:35 +0000] [64] [INFO] Worker exiting (pid: 64)
2017-01-20T11:24:35.57-0500 [APP/PROC/WEB/0]ERR [2017-01-20 16:24:35 +0000] [14] [INFO] Shutting down: Master
2017-01-20T11:24:35.57-0500 [APP/PROC/WEB/0]ERR [2017-01-20 16:24:35 +0000] [14] [INFO] Reason: Worker failed to boot.
2017-01-20T11:24:35.59-0500 [APP/PROC/WEB/0]OUT Exit status 3

Also:
```
crawles$ cat compute-tweet-stats/environment.yml
name: tweet_rate_environment
dependencies:
  - pandas
  - python=2.7.11
  - pip:
      - flask
      - gunicorn
      - redis```

**Comment by crawles** [comment]
As an update. I tried pushing same app/code. Changed build-pack to PEZ's built-in "python_buildpack" instead of "https://github.com/cloudfoundry/python-buildpack" and it worked. Think caching was causing the problem
