### ISSUE TITLE
requirements.txt does not get updated after a push command

### ISSUE THREAD

**Issue by vpekar** [cloudfoundry/python-buildpack#63]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

> cf version 6.21.1+6fd3c9f-2016-08-10

What version of the buildpack you are using?

> Versions 1.5.9-15

If you were attempting to accomplish a task, what was it you were attempting to do?

> Push updates to requirements.txt

What did you expect to happen?

> The old version of requirements.txt contained an error (inline comment that it seems was not allowed in later version of pip). I removed the comment and tried to update the requirements file on the server.

What was the actual behavior?

> The app failed to start, because pip kept complaining that the inline comment was still there.

Old version of requirements.txt contains:

```
mysql-python#==1.2.5
```

New version of requirements.txt contains:

```
mysql-python
```

Error log after pushing the new version:

```
-------> Buildpack version 1.5.10
 !     Warning: Your application is missing a Procfile. This file tells Cloud Foundry how to run your application.
 !     Learn more: https://docs.cloudfoundry.org/buildpacks/prod-server.html#procfile
Traceback (most recent call last):
  File "/tmp/buildpack/vendor/pip-pop/pip-diff", line 116, in <module>
    main()
  File "/tmp/buildpack/vendor/pip-pop/pip-diff", line 112, in main
    diff(**kwargs)
  File "/tmp/buildpack/vendor/pip-pop/pip-diff", line 84, in diff
    r1 = Requirements(r1)
  File "/tmp/buildpack/vendor/pip-pop/pip-diff", line 29, in __init__
    self.load(reqfile)
  File "/tmp/buildpack/vendor/pip-pop/pip-diff", line 39, in load
    for requirement in parse_requirements(reqfile, finder=finder, session=requests):
  File "/app/.heroku/python/lib/python2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_file.py", line 93, in parse_requirements
    for req in req_iter:
  File "/app/.heroku/python/lib/python2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_file.py", line 158, in process_line
    "Invalid requirement: '%s'\n%s" % (req, add_msg))
pip.exceptions.InstallationError: Invalid requirement: 'MySQL-python#==1.2.5'
    isolated=isolated, options=req_options, wheel_cache=wheel_cache
  File "/app/.heroku/python/lib/python2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 226, in from_line
    wheel_cache=wheel_cache, constraint=constraint)
  File "/app/.heroku/python/lib/python2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 87, in __init__
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 78, in __init__
    req = Requirement(req)
  File "/app/.heroku/python/lib/python2.7/site-packages/pip-8.1.2-py2.7.egg/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
InvalidRequirement: Invalid requirement, parse error at "u'#==1.2.5'"
Staging failed: Buildpack compilation step failed

FAILED
Error restarting application: BuildpackCompileFailed
```

The same problem happens with manifest.yml - it does not get updated if the previous installation fails.

The build succeeded with the buildpack version 1.5.9, but failed with the same error for versions 1.5.10 and up. The bug was introduced in v1.5.10.

It seems that if an installation commands exit with an error, old requirements.txt (and manifest.yml) will be used in the next push.

Please confirm where necessary:
* [X] I have included a log output
* [X] My log includes an error message
* [X] I have included steps for reproduction

**Comment by sclevine** [comment]
Hi @vpekar,

I am unable to replicate this in v1.5.10 or v1.5.14 (latest).

Each new push re-uploads your app and stages it in a new application container. (The buildpack has access to a cache directory that survives between pushes, but this directory does not contain any part of your app.)

If you delete your app completely and re-push, does this behavior go away?
Can you confirm that you haven't mistakenly pushed an old copy of your app?
If you `cf ssh` into your app and compare requirements.txt in the app container to your local version, are they different?

**Comment by vpekar** [comment]
@sclevine Exactly the same issue happened when I tried changing the manifest file. I specified a php buildpack in manifest.yml, the build failed. Then I removed the line with the buildpack in manifest.yml and pushed again, but php was still installed. When I explicitly specified a python buildpack on the command line, I was able to get rid of the php buildback.

I haven't tried deleting the app, but I am sure the issue would go away, because the issue has to do with a file not getting overwritten in a push.

I confirm I have a single copy of the app, and I verified I was pushing an updated version of requirements.txt.

I could not do `cf ssh` while the issue was there (because the app was down). Now that I switched to buildback v.1.5.9, everything works as expected.

**Comment by sclevine** [comment]
> I removed the line with the buildpack in manifest.yml and pushed again, but php was still installed. When I explicitly specified a python buildpack on the command line, I was able to get rid of the php buildback.

This is actually expected CF behavior. The buildpack is sticky -- it doesn't change unless you explicitly set it to something else.

> The issue has to do with a file not getting overwritten in a push.

CF stages each new push in an entirely separate container. It's not possible for a file from a subsequent push to remain for a new push (with the exception of the cache directory).

Can you provide a sample app and series of commands that you believe replicates the issue?

**Comment by vpekar** [comment]
The issue must be with the old version of the problematic file staying in the cache directory. It does not get overwritten with a new version in the following push, if that file contains a problem (such as an inline comment) and an error is thrown and the build stops. This behaviour started to happen with v.1.5.10.

**Comment by sclevine** [comment]
The cache directory is an entirely separate directory from the app directory. The buildpack would need to copy requirements.txt into that directory and back out again on the next stage for that to happen. This is not something that the buildpack does.

It's much more likely that you're still staging with the old app bits. And again, I am not able to reproduce this behavior in v1.5.10. I've reviewed [the changes from that version](https://github.com/cloudfoundry/python-buildpack/compare/v1.5.9...cloudfoundry:v1.5.10), and I see nothing that would lead to the behavior you describe.

If you can provide a sample app and series of commands to replicate, then we will be able to investigate further.

**Comment by sclevine** [comment]
Closing this due to inactivity. Don't hesitate to reply if you still need assistance.

**Comment by MarcMueltin** [comment]
I have the same problem: trying to deploy a Python app to Heroku for the first time. Had an error in my requirements.txt file (channels-redis-2.4.0 instead of channels-redis==2.4.0), corrected the error, did another "git push heroku master", and the deploy fails. even after deleting the heroku app and creating it anew, the deployment keeps failing, stating the same old error in the requirements.txt file on the command line - although I corrected it already.

So the error does persist, the requirements.txt file is cached in a /tmp directory somewhere where I cannot access it. This is really frustrating.

`remote: Building source:
remote: 
remote: -----> Python app detected
remote: -----> Installing python-3.6.9
remote: -----> Installing pip
remote: -----> Installing SQLite3
remote: -----> Installing requirements with pip
remote:        Collecting Django==2.2.3 (from -r /tmp/build_32b1ab50153650ab497cc9e60f2a5626/requirements.txt (line 1))
remote:          Downloading https://files.pythonhosted.org/packages/39/b0/2138c31bf13e17afc32277239da53e9dfcce27bac8cb68cf1c0123f1fdf5/Django-2.2.3-py3-none-any.whl (7.5MB)
remote:        Collecting class-registry==2.1.2 (from -r /tmp/build_32b1ab50153650ab497cc9e60f2a5626/requirements.txt (line 4))
remote:          Downloading https://files.pythonhosted.org/packages/05/ca/3723cb3a74a23fe77c88f29fe06fed202acc398763d36b6721dc2883bbd4/class_registry-2.1.2-py2.py3-none-any.whl
remote:        Collecting channels==2.2.0 (from -r /tmp/build_32b1ab50153650ab497cc9e60f2a5626/requirements.txt (line 7))
remote:          Downloading https://files.pythonhosted.org/packages/80/44/8344737fcd2b103b67793d87a790a6c2bdf9a468ea98181f0c87b0d603e7/channels-2.2.0-py2.py3-none-any.whl
remote:        Collecting websocket_client==0.56.0 (from -r /tmp/build_32b1ab50153650ab497cc9e60f2a5626/requirements.txt (line 8))
remote:          Downloading https://files.pythonhosted.org/packages/29/19/44753eab1fdb50770ac69605527e8859468f3c0fd7dc5a76dd9c4dbd7906/websocket_client-0.56.0-py2.py3-none-any.whl (200kB)
remote:        Collecting psycopg2-binary==2.8.3 (from -r /tmp/build_32b1ab50153650ab497cc9e60f2a5626/requirements.txt (line 9))
remote:          Downloading https://files.pythonhosted.org/packages/b1/35/75c9c2d9cfc073ab6c42b2d8e91ff58c9b99f4ed7ed56b36647642e6080e/psycopg2_binary-2.8.3-cp36-cp36m-manylinux1_x86_64.whl (2.9MB)
remote:        Collecting channels-redis-2.4.0 (from -r /tmp/build_32b1ab50153650ab497cc9e60f2a5626/requirements.txt (line 10))
remote:          Could not find a version that satisfies the requirement channels-redis-2.4.0 (from -r /tmp/build_32b1ab50153650ab497cc9e60f2a5626/requirements.txt (line 10)) (from versions: )
remote:        No matching distribution found for channels-redis-2.4.0 (from -r /tmp/build_32b1ab50153650ab497cc9e60f2a5626/requirements.txt (line 10))
remote:  !     Push rejected, failed to compile Python app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to afternoon-reef-50098.`

**Comment by YouCantTouchThis** [comment]
I had the same issue. You have to change requirements.txt, then git add requirements.txt, git commit and then rerun your heroku push. It's a bit annoying but this is how I got it to work.
