### ISSUE TITLE
pip -e issue

### ISSUE THREAD

**Issue by cmc333333** [cloudfoundry/python-buildpack#64]
This *may* be the problem raised upstream: https://github.com/heroku/heroku-buildpack-python/issues/352

## What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

* API: 2.68.0
* CLI: 6.23.1+a70deb3.2017-01-13

## What version of the buildpack you are using?

1.5.14

## If you were attempting to accomplish a task, what was it you were attempting to do?

Deploy an application with a `-e`ditable library in its requirements.txt.

## What did you expect to happen?

For the application to include the editable library in its PYTHONPATH.

## What was the actual behavior?

Editable library could not be found.

## Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

Cleaned up logs:
```sh
$ ls
Procfile  requirements.txt  run.py
$ cat Procfile
web: python run.py
$ cat requirements.txt
-e git+https://github.com/eregs/regulations-core.git@2.0.0#egg=regcore

$ cat run.py
from regcore import settings
$ cf push fail
Updating app fail in org [SNIP] / space [SNIP] as [SNIP]...
OK

Uploading fail...
Uploading app files from: /tmp/fail
Uploading 494B, 3 files
Done uploading
OK

Starting app fail in org [SNIP] / space [SNIP] as [SNIP]...
Downloading binary_buildpack...
Downloading nodejs_buildpack...
Downloading go_buildpack...
Downloading python_buildpack...
Downloading ruby_buildpack...
Downloaded binary_buildpack
Downloading staticfile_buildpack...
Downloaded go_buildpack
Downloading java_buildpack...
Downloaded ruby_buildpack
Downloading php_buildpack...
Downloaded nodejs_buildpack
Downloading dotnet_core_buildpack...
Downloaded python_buildpack
Downloaded staticfile_buildpack
Downloaded php_buildpack
Downloaded java_buildpack
Downloaded dotnet_core_buildpack
Creating container
Successfully created container
Downloading app package...
Downloaded app package (581B)
Staging...
-------> Buildpack version 1.5.14
-----> Installing python-2.7.12
**WARNING** A newer version of python is available in this buildpack. Please adjust your app to use version 2.7.13 instead of version 2.7.12 as soon as possible. Old versions of python are only provided to assist in migrating to newer versions.
Downloaded [file:///tmp/buildpack/dependencies/https___buildpacks.cloudfoundry.org_dependencies_python_python-2.7.12-linux-x64.tgz]
     $ pip install -r requirements.txt
       Obtaining regcore from git+https://github.com/eregs/regulations-core.git@2.0.0#egg=regcore (from -r requirements.txt (line 1))
         Cloning https://github.com/eregs/regulations-core.git (to 2.0.0) to ./.heroku/src/regcore
       Collecting django<1.10,>=1.8 (from regcore->-r requirements.txt (line 1))
         Downloading Django-1.9.12-py2.py3-none-any.whl (6.6MB)
       Collecting django-mptt (from regcore->-r requirements.txt (line 1))
         Downloading django_mptt-0.8.7-py2.py3-none-any.whl (96kB)
       Collecting jsonschema (from regcore->-r requirements.txt (line 1))
         Downloading jsonschema-2.6.0-py2.py3-none-any.whl
       Collecting six (from regcore->-r requirements.txt (line 1))
         Downloading six-1.10.0-py2.py3-none-any.whl
       Collecting functools32; python_version == "2.7" (from jsonschema->regcore->-r requirements.txt (line 1))
         Downloading functools32-3.2.3-2.zip
       Installing collected packages: django, django-mptt, functools32, jsonschema, six, regcore
         Running setup.py install for functools32: started
           Running setup.py install for functools32: finished with status 'done'
         Running setup.py develop for regcore
       Successfully installed django-1.9.12 django-mptt-0.8.7 functools32-3.2.3.post2 jsonschema-2.6.0 regcore six-1.10.0
Exit status 0
Staging complete
Uploading droplet, build artifacts cache...
Uploading droplet...
Uploading build artifacts cache...
Uploaded build artifacts cache (34.8M)
Uploaded droplet (34.9M)
Uploading complete
Destroying container
Successfully destroyed container

0 of 1 instances running, 1 starting
0 of 1 instances running, 1 crashed
FAILED
Error restarting application: Start unsuccessful

TIP: use 'cf logs fail --recent' for more information
$ cf logs fail --recent
Connected, dumping recent logs for app fail in org [SNIP] / space [SNIP] as [SNIP]...

2017-02-09T16:03:59.54+0000 [API/0]      OUT Created app with guid 12e6ac12-e265-41ba-b958-efa89cb9af30
2017-02-09T16:04:03.19+0000 [API/1]      OUT Updated app with guid 12e6ac12-e265-41ba-b958-efa89cb9af30 ({"route"=>"dfac10db-0dd5-42cc-a4ba-e7c8b96b212c", :verb=>"add", :relation=>"routes", :related_guid=>"dfac10db-0dd5-42cc-a4ba-e7c8b96b212c"})
2017-02-09T16:06:09.59+0000 [API/0]      OUT Updated app with guid 12e6ac12-e265-41ba-b958-efa89cb9af30 ({"name"=>"fail"})
2017-02-09T16:06:22.76+0000 [API/0]      OUT Updated app with guid 12e6ac12-e265-41ba-b958-efa89cb9af30 ({"state"=>"STARTED"})
2017-02-09T16:06:22.78+0000 [STG/0]      OUT Downloading binary_buildpack...
2017-02-09T16:06:22.78+0000 [STG/0]      OUT Downloading nodejs_buildpack...
2017-02-09T16:06:22.78+0000 [STG/0]      OUT Downloading go_buildpack...
2017-02-09T16:06:22.78+0000 [STG/0]      OUT Downloading python_buildpack...
2017-02-09T16:06:22.78+0000 [STG/0]      OUT Downloading ruby_buildpack...
2017-02-09T16:06:22.79+0000 [STG/0]      OUT Downloaded binary_buildpack
2017-02-09T16:06:22.79+0000 [STG/0]      OUT Downloading staticfile_buildpack...
2017-02-09T16:06:22.79+0000 [STG/0]      OUT Downloaded go_buildpack
2017-02-09T16:06:22.79+0000 [STG/0]      OUT Downloading java_buildpack...
2017-02-09T16:06:22.80+0000 [STG/0]      OUT Downloaded ruby_buildpack
2017-02-09T16:06:22.80+0000 [STG/0]      OUT Downloading php_buildpack...
2017-02-09T16:06:22.80+0000 [STG/0]      OUT Downloaded nodejs_buildpack
2017-02-09T16:06:22.81+0000 [STG/0]      OUT Downloading dotnet_core_buildpack...
2017-02-09T16:06:22.81+0000 [STG/0]      OUT Downloaded python_buildpack
2017-02-09T16:06:22.81+0000 [STG/0]      OUT Downloaded staticfile_buildpack
2017-02-09T16:06:22.82+0000 [STG/0]      OUT Downloaded php_buildpack
2017-02-09T16:06:22.82+0000 [STG/0]      OUT Downloaded java_buildpack
2017-02-09T16:06:22.83+0000 [STG/0]      OUT Downloaded dotnet_core_buildpack
2017-02-09T16:06:22.83+0000 [STG/0]      OUT Creating container
2017-02-09T16:06:23.41+0000 [STG/0]      OUT Successfully created container
2017-02-09T16:06:23.41+0000 [STG/0]      OUT Downloading app package...
2017-02-09T16:06:23.45+0000 [STG/0]      OUT Downloaded app package (581B)
2017-02-09T16:06:23.45+0000 [STG/0]      OUT Staging...
2017-02-09T16:06:25.35+0000 [STG/0]      OUT -------> Buildpack version 1.5.14
2017-02-09T16:06:25.45+0000 [STG/0]      OUT -----> Installing python-2.7.12
2017-02-09T16:06:25.79+0000 [STG/0]      OUT **WARNING** A newer version of python is available in this buildpack. Please adjust your app to use version 2.7.13 instead of version 2.7.12 as soon as possible. Old versions of python are only provided to assist in migrating to newer versions.
2017-02-09T16:06:26.72+0000 [STG/0]      OUT Downloaded [file:///tmp/buildpack/dependencies/https___buildpacks.cloudfoundry.org_dependencies_python_python-2.7.12-linux-x64.tgz]
2017-02-09T16:06:33.11+0000 [STG/0]      OUT      $ pip install -r requirements.txt
2017-02-09T16:06:34.08+0000 [STG/0]      OUT        Obtaining regcore from git+https://github.com/eregs/regulations-core.git@2.0.0#egg=regcore (from -r requirements.txt (line 1))
2017-02-09T16:06:34.08+0000 [STG/0]      OUT          Cloning https://github.com/eregs/regulations-core.git (to 2.0.0) to ./.heroku/src/regcore
2017-02-09T16:06:38.08+0000 [STG/0]      OUT        Collecting django<1.10,>=1.8 (from regcore->-r requirements.txt (line 1))
2017-02-09T16:06:38.29+0000 [STG/0]      OUT          Downloading Django-1.9.12-py2.py3-none-any.whl (6.6MB)
2017-02-09T16:06:40.52+0000 [STG/0]      OUT        Collecting django-mptt (from regcore->-r requirements.txt (line 1))
2017-02-09T16:06:40.57+0000 [STG/0]      OUT          Downloading django_mptt-0.8.7-py2.py3-none-any.whl (96kB)
2017-02-09T16:06:40.70+0000 [STG/0]      OUT        Collecting jsonschema (from regcore->-r requirements.txt (line 1))
2017-02-09T16:06:40.75+0000 [STG/0]      OUT          Downloading jsonschema-2.6.0-py2.py3-none-any.whl
2017-02-09T16:06:40.87+0000 [STG/0]      OUT        Collecting six (from regcore->-r requirements.txt (line 1))
2017-02-09T16:06:40.92+0000 [STG/0]      OUT          Downloading six-1.10.0-py2.py3-none-any.whl
2017-02-09T16:06:41.11+0000 [STG/0]      OUT        Collecting functools32; python_version == "2.7" (from jsonschema->regcore->-r requirements.txt (line 1))
2017-02-09T16:06:41.15+0000 [STG/0]      OUT          Downloading functools32-3.2.3-2.zip
2017-02-09T16:06:41.53+0000 [STG/0]      OUT        Installing collected packages: django, django-mptt, functools32, jsonschema, six, regcore
2017-02-09T16:06:44.78+0000 [STG/0]      OUT          Running setup.py install for functools32: started
2017-02-09T16:06:45.23+0000 [STG/0]      OUT            Running setup.py install for functools32: finished with status 'done'
2017-02-09T16:06:45.30+0000 [STG/0]      OUT          Running setup.py develop for regcore
2017-02-09T16:06:45.78+0000 [STG/0]      OUT        Successfully installed django-1.9.12 django-mptt-0.8.7 functools32-3.2.3.post2 jsonschema-2.6.0 regcore six-1.10.0
2017-02-09T16:07:08.53+0000 [STG/0]      OUT Exit status 0
2017-02-09T16:07:08.53+0000 [STG/0]      OUT Staging complete
2017-02-09T16:07:08.53+0000 [STG/0]      OUT Uploading droplet, build artifacts cache...
2017-02-09T16:07:08.53+0000 [STG/0]      OUT Uploading droplet...
2017-02-09T16:07:08.53+0000 [STG/0]      OUT Uploading build artifacts cache...
2017-02-09T16:07:09.39+0000 [STG/0]      OUT Uploaded build artifacts cache (34.8M)
2017-02-09T16:07:13.46+0000 [STG/0]      OUT Uploaded droplet (34.9M)
2017-02-09T16:07:13.47+0000 [STG/0]      OUT Uploading complete
2017-02-09T16:07:13.50+0000 [STG/0]      OUT Destroying container
2017-02-09T16:07:13.92+0000 [CELL/0]     OUT Creating container
2017-02-09T16:07:14.33+0000 [CELL/0]     OUT Successfully created container
2017-02-09T16:07:17.06+0000 [STG/0]      OUT Successfully destroyed container
2017-02-09T16:07:17.27+0000 [CELL/0]     OUT Starting health monitoring of container
2017-02-09T16:07:17.40+0000 [APP/PROC/WEB/0]ERR Traceback (most recent call last):
2017-02-09T16:07:17.40+0000 [APP/PROC/WEB/0]ERR   File "run.py", line 1, in <module>
2017-02-09T16:07:17.40+0000 [APP/PROC/WEB/0]ERR     from regcore import settings
2017-02-09T16:07:17.40+0000 [APP/PROC/WEB/0]ERR ImportError: No module named regcore
2017-02-09T16:07:17.40+0000 [APP/PROC/WEB/0]OUT Exit status 1
2017-02-09T16:07:17.43+0000 [CELL/0]     OUT Exit status 0
2017-02-09T16:07:17.44+0000 [CELL/0]     OUT Destroying container
2017-02-09T16:07:17.46+0000 [CELL/0]     OUT Creating container
2017-02-09T16:07:17.51+0000 [API/1]      OUT Process has crashed with type: "web"
2017-02-09T16:07:17.52+0000 [API/1]      OUT App instance exited with guid 12e6ac12-e265-41ba-b958-efa89cb9af30 payload: {"instance"=>"", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* 2 error(s) occurred:\n\n* Exited with status 1\n* cancelled\n* cancelled", "crash_count"=>1, "crash_timestamp"=>1486656437383732812, "version"=>"c491202f-9e84-48c9-81ae-29f3c475eee0"}
2017-02-09T16:07:17.97+0000 [CELL/0]     OUT Successfully created container
2017-02-09T16:07:18.58+0000 [CELL/0]     OUT Successfully destroyed container
2017-02-09T16:07:20.93+0000 [CELL/0]     OUT Starting health monitoring of container
2017-02-09T16:07:21.03+0000 [APP/PROC/WEB/0]ERR Traceback (most recent call last):
2017-02-09T16:07:21.03+0000 [APP/PROC/WEB/0]ERR   File "run.py", line 1, in <module>
2017-02-09T16:07:21.03+0000 [APP/PROC/WEB/0]ERR     from regcore import settings
2017-02-09T16:07:21.03+0000 [APP/PROC/WEB/0]ERR ImportError: No module named regcore
2017-02-09T16:07:21.03+0000 [APP/PROC/WEB/0]OUT Exit status 1
2017-02-09T16:07:21.04+0000 [CELL/0]     OUT Exit status 0
2017-02-09T16:07:21.06+0000 [CELL/0]     OUT Destroying container
2017-02-09T16:07:21.07+0000 [API/0]      OUT Process has crashed with type: "web"
2017-02-09T16:07:21.09+0000 [CELL/0]     OUT Creating container
2017-02-09T16:07:21.09+0000 [API/0]      OUT App instance exited with guid 12e6ac12-e265-41ba-b958-efa89cb9af30 payload: {"instance"=>"", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* 2 error(s) occurred:\n\n* Exited with status 1\n* cancelled\n* cancelled", "crash_count"=>2, "crash_timestamp"=>1486656441006021356, "version"=>"c491202f-9e84-48c9-81ae-29f3c475eee0"}
2017-02-09T16:07:21.59+0000 [CELL/0]     OUT Successfully created container
2017-02-09T16:07:22.05+0000 [CELL/0]     OUT Successfully destroyed container
2017-02-09T16:07:24.48+0000 [CELL/0]     OUT Starting health monitoring of container
2017-02-09T16:07:24.60+0000 [API/0]      OUT Process has crashed with type: "web"
2017-02-09T16:07:24.61+0000 [API/0]      OUT App instance exited with guid 12e6ac12-e265-41ba-b958-efa89cb9af30 payload: {"instance"=>"", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* 2 error(s) occurred:\n\n* Exited with status 1\n* cancelled\n* cancelled", "crash_count"=>3, "crash_timestamp"=>1486656444595604386, "version"=>"c491202f-9e84-48c9-81ae-29f3c475eee0"}
2017-02-09T16:07:24.62+0000 [APP/PROC/WEB/0]ERR Traceback (most recent call last):
2017-02-09T16:07:24.62+0000 [APP/PROC/WEB/0]ERR   File "run.py", line 1, in <module>
2017-02-09T16:07:24.62+0000 [APP/PROC/WEB/0]ERR     from regcore import settings
2017-02-09T16:07:24.62+0000 [APP/PROC/WEB/0]ERR ImportError: No module named regcore
2017-02-09T16:07:24.62+0000 [APP/PROC/WEB/0]OUT Exit status 1
2017-02-09T16:07:24.64+0000 [CELL/0]     OUT Exit status 0
2017-02-09T16:07:24.64+0000 [CELL/0]     OUT Destroying container
2017-02-09T16:07:25.76+0000 [CELL/0]     OUT Successfully destroyed container
2017-02-09T16:08:17.95+0000 [CELL/0]     OUT Creating container
2017-02-09T16:08:18.42+0000 [CELL/0]     OUT Successfully created container
2017-02-09T16:08:21.64+0000 [CELL/0]     OUT Starting health monitoring of container
2017-02-09T16:08:21.78+0000 [APP/PROC/WEB/0]ERR Traceback (most recent call last):
2017-02-09T16:08:21.78+0000 [APP/PROC/WEB/0]ERR   File "run.py", line 1, in <module>
2017-02-09T16:08:21.78+0000 [APP/PROC/WEB/0]ERR     from regcore import settings
2017-02-09T16:08:21.78+0000 [APP/PROC/WEB/0]ERR ImportError: No module named regcore
2017-02-09T16:08:21.78+0000 [APP/PROC/WEB/0]OUT Exit status 1
2017-02-09T16:08:21.80+0000 [CELL/0]     OUT Exit status 0
2017-02-09T16:08:21.82+0000 [CELL/0]     OUT Destroying container
2017-02-09T16:08:21.82+0000 [API/0]      OUT Process has crashed with type: "web"
2017-02-09T16:08:21.84+0000 [API/0]      OUT App instance exited with guid 12e6ac12-e265-41ba-b958-efa89cb9af30 payload: {"instance"=>"", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* 2 error(s) occurred:\n\n* Exited with status 1\n* cancelled\n* cancelled", "crash_count"=>4, "crash_timestamp"=>1486656501761272238, "version"=>"c491202f-9e84-48c9-81ae-29f3c475eee0"}
2017-02-09T16:08:23.07+0000 [CELL/0]     OUT Successfully destroyed container
```

If I remove the `-e` from my requirements.txt, I don't get the import error anymore.

**Comment by sclevine** [comment]
Thanks for the report, and sorry for the delayed response. An investigation into this has been prioritized.

**Comment by sesmith177** [comment]
@cmc333333 we have pushed a commit to develop: b599447a88ca3f110d416d7d3a964e3807110a15 that should fix this.

Can you test by pushing your app with `-b https://github.com/cloudfoundry/python-buildpack#develop` ?

Thanks.

**Comment by sclevine** [comment]
FIxed in the latest release.
