### ISSUE TITLE
dbm missing from python standard library

### ISSUE THREAD

**Issue by wuftymerguftyguff** [cloudfoundry/python-buildpack#83]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

{
   "name": "",
   "build": "",
   "support": "https://help.cf.eu10.hana.ondemand.com",
   "version": 0,
   "description": "Cloud Foundry at SAP Cloud Platform",
   "authorization_endpoint": "https://login.cf.eu10.hana.ondemand.com",
   "token_endpoint": "https://uaa.cf.eu10.hana.ondemand.com",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "api_version": "2.89.0",
   "app_ssh_endpoint": "ssh.cf.eu10.hana.ondemand.com:2222",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.cf.eu10.hana.ondemand.com:443"
}
 

cf version 6.29.0+ff886fa93.2017-07-24

What version of the buildpack you are using?

latest from git (1.5.22)

If you were attempting to accomplish a task, what was it you were attempting to do?

upload a python app that uses dim from the python standard library

What did you expect to happen?

my app to start

What was the actual behavior?

app crashes on start

 2017-07-30T15:19:21.87+0100 [APP/PROC/WEB/0] ERR Traceback (most recent call last):
   2017-07-30T15:19:21.87+0100 [APP/PROC/WEB/0] ERR   File "helloworld.py", line 6, in <module>
   2017-07-30T15:19:21.87+0100 [APP/PROC/WEB/0] ERR     import dbm
   2017-07-30T15:19:21.87+0100 [APP/PROC/WEB/0] ERR ImportError: No module named dbm

To recreate deploy a python app that imports dbm

e.g.

requirements.txt
```
Flask
Gunicorn
```

manifest.yml

```
---
applications:
- name: atestapp
  memory: 128M
  command: python helloworld.py
  buildpack: https://github.com/cloudfoundry/buildpack-python.git
```

helloworld.py

```
from flask import Flask
import os
import dbm

app = Flask(__name__)

port = int(os.getenv("PORT", 9009))

@app.route('/')
def hello_world():
        return 'Hello World!'

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=port)
```

if you remove the import dam, app starts fine.

Please confirm where necessary:
* [X] I have included a log output
* [X] My log includes an error message
* [X] I have included steps for reproduction

**Comment by sclevine** [comment]
Waiting on questions in slack: https://cloudfoundry.slack.com/archives/C02HWMDUQ/p1501436076263711

**Comment by wuftymerguftyguff** [comment]
App imports pysaml2, which assumes that dbm is compiled into python.

2017-07-30T19:37:39.51+0100 [APP/PROC/WEB/0] ERR Traceback (most recent call last):
   2017-07-30T19:37:39.51+0100 [APP/PROC/WEB/0] ERR   File "./idp.py", line 22, in <module>
   2017-07-30T19:37:39.51+0100 [APP/PROC/WEB/0] ERR     from saml2 import server
   2017-07-30T19:37:39.51+0100 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/saml2/server.py", line 12, in <module>
   2017-07-30T19:37:39.51+0100 [APP/PROC/WEB/0] ERR     import dbm
   2017-07-30T19:37:39.51+0100 [APP/PROC/WEB/0] ERR ImportError: No module named dbm

**Comment by wuftymerguftyguff** [comment]
FWIW I was able to build a python that included dam using your configure settings by including the dependency libdb-dev with apt-get

**Comment by sclevine** [comment]
This should be addressed in the next release of the buildpack.
