### ISSUE TITLE
Vendored dependencies, but easy_install still tries to pull down from pypi

### ISSUE THREAD

**Issue by mguarascio** [cloudfoundry/python-buildpack#96]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
{
   "name": "",
   "build": "",
   "support": "https://support.pivotal.io",
   "version": 0,
   "description": "",
   "authorization_endpoint": "*************",
   "token_endpoint": "*************",
   "min_cli_version": "6.23.0",
   "min_recommended_cli_version": "6.23.0",
   "api_version": "2.82.0",
   "app_ssh_endpoint": "*************",
   "app_ssh_host_key_fingerprint": "*************",
   "app_ssh_oauth_client": "ssh-proxy",
   "routing_endpoint": "*************",
   "doppler_logging_endpoint": "*************"
}

What version of the buildpack you are using?
1.5.26 (and receive same error with 1.6.2)

If you were attempting to accomplish a task, what was it you were attempting to do?
cf push with vendored dependencies, following the guidelines here: https://docs.cloudfoundry.org/buildpacks/python/index.html#vendoring

What did you expect to happen?
pip install to use the locally vendored dependencies, without reaching out to pypi.org

What was the actual behavior?
An easy_install command was run, which tried to pull down a transitive dependency. This caused the cf push to fail since our Cloud Foundry environments are disconnected from the Internet

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Commands run to vendor dependencies on build machine:**

```
mkdir env  
python3 -m venv env  
. env/bin/activate  

echo "[easy_install]
index_url=<internal artifactory which proxies pypi>
" > ~/.pydistutils.cfg

cat ~/.pydistutils.cfg

pip3 download -d vendor -i <internal artifactory which proxies pypi> -r requirements.txt --no-binary :all:
```

Note: I also tried including the pbr .whl file directly in the vendor subfolder, but this did not work. 

**Log Output:** 
```
simple	19-Jan-2018 09:45:41	2018-01-19T09:45.41-0500 [STG/0]      OUT Downloading python_current...
simple	19-Jan-2018 09:45:49	2018-01-19T09:45.50-0500 [STG/0]      OUT Creating container
simple	19-Jan-2018 09:45:49	2018-01-19T09:45.50-0500 [STG/0]      OUT Downloaded python_current (345.4M)
simple	19-Jan-2018 09:45:50	2018-01-19T09:45.51-0500 [STG/0]      OUT Successfully created container
simple	19-Jan-2018 09:45:50	2018-01-19T09:45.51-0500 [STG/0]      OUT Downloading app package...
simple	19-Jan-2018 09:45:51	2018-01-19T09:45.52-0500 [STG/0]      OUT Downloaded app package (21.4M)
simple	19-Jan-2018 09:45:51	2018-01-19T09:45.52-0500 [STG/0]      OUT Staging...
simple	19-Jan-2018 09:45:51	2018-01-19T09:45.52-0500 [STG/0]      OUT -------> Buildpack version 1.5.26
simple	19-Jan-2018 09:45:52	2018-01-19T09:45.52-0500 [STG/0]      OUT -----> Installing python-3.6.2
simple	19-Jan-2018 09:45:54	2018-01-19T09:45.54-0500 [STG/0]      OUT Downloaded [file:///tmp/buildpacks/31b7c3877ad50f879fbb22278024c196/dependencies/https___buildpacks.cloudfoundry.org_dependencies_python_python-3.6.2-linux-x64-4fdb9c31.tgz]
simple	19-Jan-2018 09:45:54	2018-01-19T09:45.54-0500 [STG/0]      OUT -----> Installing Setuptools (32.1.0)
simple	19-Jan-2018 09:45:54	2018-01-19T09:45.54-0500 [STG/0]      OUT Downloaded [file:///tmp/buildpacks/31b7c3877ad50f879fbb22278024c196/dependencies/https___buildpacks.cloudfoundry.org_dependencies_manual-binaries_setuptools_setuptools-32.1.0-44054eaa.tar.gz]
simple	19-Jan-2018 09:45:56	2018-01-19T09:45.56-0500 [STG/0]      OUT -----> Installing Pip (9.0.1)
simple	19-Jan-2018 09:45:56	2018-01-19T09:45.56-0500 [STG/0]      OUT Downloaded [file:///tmp/buildpacks/31b7c3877ad50f879fbb22278024c196/dependencies/https___buildpacks.cloudfoundry.org_dependencies_manual-binaries_pip_pip-9.0.1-35f01da3.tar.gz]
simple	19-Jan-2018 09:45:59	2018-01-19T09:45.59-0500 [STG/0]      OUT -----> Installing pip-pop (0.1.1)
simple	19-Jan-2018 09:45:59	2018-01-19T09:45.59-0500 [STG/0]      OUT Downloaded [file:///tmp/buildpacks/31b7c3877ad50f879fbb22278024c196/dependencies/https___buildpacks.cloudfoundry.org_dependencies_manual-binaries_pip-pop_pip-pop-0.1.1-d410583a.tar.gz]
simple	19-Jan-2018 09:46:02	2018-01-19T09:46.02-0500 [STG/0]      OUT -----> Installing pipenv (4.0.1)
simple	19-Jan-2018 09:46:02	2018-01-19T09:46.03-0500 [STG/0]      OUT Downloaded [file:///tmp/buildpacks/31b7c3877ad50f879fbb22278024c196/dependencies/https___buildpacks.cloudfoundry.org_dependencies_manual-binaries_pipenv_pipenv-4.0.1-148f753f.tar.gz]
simple	19-Jan-2018 09:46:15	2018-01-19T09:46.15-0500 [STG/0]      OUT      $ pip install -r requirements.txt
simple	19-Jan-2018 09:46:15	2018-01-19T09:46.16-0500 [STG/0]      OUT        Collecting Flask (from -r requirements.txt (line 1))
simple	19-Jan-2018 09:46:16	2018-01-19T09:46.16-0500 [STG/0]      OUT        Collecting redis (from -r requirements.txt (line 2))
simple	19-Jan-2018 09:46:17	2018-01-19T09:46.17-0500 [STG/0]      OUT        Collecting vcappy (from -r requirements.txt (line 3))
simple	19-Jan-2018 09:46:17	2018-01-19T09:46.18-0500 [STG/0]      OUT        Collecting lmcrypto (from -r requirements.txt (line 4))
simple	19-Jan-2018 09:46:18	2018-01-19T09:46.18-0500 [STG/0]      OUT        Collecting waitress (from -r requirements.txt (line 5))
simple	19-Jan-2018 09:46:19	2018-01-19T09:46.19-0500 [STG/0]      OUT        Collecting pyramid_swagger (from -r requirements.txt (line 6))
simple	19-Jan-2018 09:46:19	2018-01-19T09:46.19-0500 [STG/0]      OUT        Collecting pymongo (from -r requirements.txt (line 7))
simple	19-Jan-2018 09:46:20	2018-01-19T09:46.20-0500 [STG/0]      OUT        Collecting selenium (from -r requirements.txt (line 8))
simple	19-Jan-2018 09:46:21	2018-01-19T09:46.21-0500 [STG/0]      OUT        Collecting mock (from -r requirements.txt (line 9))
simple	19-Jan-2018 09:46:56	2018-01-19T09:46.57-0500 [STG/0]      OUT            Download error on https://pypi.python.org/simple/pbr/: [Errno -2] Name or service not known -- Some packages may not be found!
simple	19-Jan-2018 09:46:56	2018-01-19T09:46.57-0500 [STG/0]      OUT            Traceback (most recent call last):
simple	19-Jan-2018 09:46:56	2018-01-19T09:46.57-0500 [STG/0]      OUT              File "/tmp/pip-build-bfl91cs0/mock/setup.py", line 6, in <module>
simple	19-Jan-2018 09:46:56	2018-01-19T09:46.57-0500 [STG/0]      OUT              File "/tmp/contents356612883/deps/0/python/lib/python3.6/site-packages/setuptools-32.1.0-py3.6.egg/setuptools/dist.py", line 371, in fetch_build_eggs
simple	19-Jan-2018 09:46:56	2018-01-19T09:46.57-0500 [STG/0]      OUT              File "/tmp/contents356612883/deps/0/python/lib/python3.6/site-packages/setuptools-32.1.0-py3.6.egg/pkg_resources/__init__.py", line 1118, in best_match
simple	19-Jan-2018 09:46:56	2018-01-19T09:46.57-0500 [STG/0]      OUT            distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pbr>=1.3')
simple	19-Jan-2018 09:46:56	2018-01-19T09:46.57-0500 [STG/0]      OUT            
simple	19-Jan-2018 09:46:56	2018-01-19T09:46.57-0500 [STG/0]      OUT            ----------------------------------------
simple	19-Jan-2018 09:46:56	2018-01-19T09:46.57-0500 [STG/0]      OUT              File "/tmp/contents356612883/deps/0/python/lib/python3.6/site-packages/setuptools-32.1.0-py3.6.egg/setuptools/dist.py", line 439, in fetch_build_egg
simple	19-Jan-2018 09:46:56	2018-01-19T09:46.57-0500 [STG/0]      OUT              File "/tmp/contents356612883/deps/0/python/lib/python3.6/site-packages/setuptools-32.1.0-py3.6.egg/setuptools/command/easy_install.py", line 659, in easy_install
simple	19-Jan-2018 09:46:56	2018-01-19T09:46.57-0500 [STG/0]      OUT            Complete output from command python setup.py egg_info:
simple	19-Jan-2018 09:46:56	2018-01-19T09:46.57-0500 [STG/0]      OUT            Couldn't find index page for 'pbr' (maybe misspelled?)
simple	19-Jan-2018 09:46:56	2018-01-19T09:46.57-0500 [STG/0]      OUT            Download error on https://pypi.python.org/simple/: [Errno -2] Name or service not known -- Some packages may not be found!
simple	19-Jan-2018 09:46:56	2018-01-19T09:46.57-0500 [STG/0]      OUT              File "<string>", line 1, in <module>
simple	19-Jan-2018 09:46:56	2018-01-19T09:46.57-0500 [STG/0]      OUT            No local packages or working download links found for pbr>=1.3
simple	19-Jan-2018 09:46:56	2018-01-19T09:46.57-0500 [STG/0]      OUT                pbr=True)
simple	19-Jan-2018 09:46:56	2018-01-19T09:46.57-0500 [STG/0]      OUT              File "/tmp/contents356612883/deps/0/python/lib/python3.6/distutils/core.py", line 108, in setup
simple	19-Jan-2018 09:46:56	2018-01-19T09:46.57-0500 [STG/0]      OUT                _setup_distribution = dist = klass(attrs)
simple	19-Jan-2018 09:46:56	2018-01-19T09:46.57-0500 [STG/0]      OUT              File "/tmp/contents356612883/deps/0/python/lib/python3.6/site-packages/setuptools-32.1.0-py3.6.egg/pkg_resources/__init__.py", line 846, in resolve
simple	19-Jan-2018 09:46:56	2018-01-19T09:46.57-0500 [STG/0]      OUT              File "/tmp/contents356612883/deps/0/python/lib/python3.6/site-packages/setuptools-32.1.0-py3.6.egg/setuptools/dist.py", line 316, in __init__
simple	19-Jan-2018 09:46:56	2018-01-19T09:46.57-0500 [STG/0]      OUT              File "/tmp/contents356612883/deps/0/python/lib/python3.6/site-packages/setuptools-32.1.0-py3.6.egg/pkg_resources/__init__.py", line 1130, in obtain
simple	19-Jan-2018 09:46:56	2018-01-19T09:46.57-0500 [STG/0]      ERR Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-bfl91cs0/mock/
simple	19-Jan-2018 09:46:56	2018-01-19T09:46.57-0500 [STG/0]      ERR Failed to compile droplet: Failed to run all supply scripts: exit status 1
simple	19-Jan-2018 09:46:56	2018-01-19T09:46.57-0500 [STG/0]      OUT Exit status 223
simple	19-Jan-2018 09:46:56	2018-01-19T09:46.57-0500 [STG/0]      ERR Staging failed: STG: Exited with status 223
simple	19-Jan-2018 09:46:56	2018-01-19T09:46.57-0500 [STG/0]      OUT Stopping instance 72e07a91-c518-4bd1-bc94-f9cad8b785c1
simple	19-Jan-2018 09:46:56	2018-01-19T09:46.57-0500 [STG/0]      OUT Destroying container
```

**Comment by mguarascio** [comment]
I was able to get past this by ensuring the transitive dependencies were included in the requirements.txt file, and for [jsonschema](https://github.com/Julian/jsonschema/issues/276) specifically, because it uses `setup_requires`, including a `~/.pydistutils.cfg` which points to the dependencies needed by that package.

Closing the issue, since this is unrelated to anything in the buildpack.
