### ISSUE TITLE
Could not install pip packages

### ISSUE THREAD

**Issue by rbp1983** [cloudfoundry/python-buildpack#97]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
cf version 6.32.0+0191c33d9.2017-09-26

What version of the buildpack you are using?

If you were attempting to accomplish a task, what was it you were attempting to do?
I was trying to do a cf push to an app that is already running

What did you expect to happen?
Update completes per normal, as its only an image change

What was the actual behavior?
Fails when installing django
  File "django/utils/version.py", line 61, in <module>
               @functools.lru_cache()
           AttributeError: 'module' object has no attribute 'lru_cache'

Error Msg:
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-WDk2ws/django/
       **ERROR** Could not install pip packages: Couldn't run pip: exit status 1
Failed to compile droplet: Failed to run all supply scripts: exit status 14
Exit status 223
Stopping instance d2dab54d-29b5-475c-8b14-c19a74a7a810
Destroying container
Successfully destroyed container

from cf logs

   2018-01-23T11:02:35.82+0800 [STG/0] OUT        Collecting django (from image==1.4.4->-r /tmp/contents388717611/deps/0/requirements.txt (line 12))
   2018-01-23T11:02:36.18+0800 [STG/0] OUT          Downloading Django-2.0.tar.gz (8.0MB)
   2018-01-23T11:02:41.33+0800 [STG/0] OUT            Complete output from command python setup.py egg_info:
   2018-01-23T11:02:41.33+0800 [STG/0] OUT            Traceback (most recent call last):
   2018-01-23T11:02:41.34+0800 [STG/0] OUT              File "<string>", line 1, in <module>
   2018-01-23T11:02:41.34+0800 [STG/0] OUT              File "/tmp/pip-build-IM9rTs/django/setup.py", line 32, in <module>
   2018-01-23T11:02:41.34+0800 [STG/0] OUT                version = __import__('django').get_version()
   2018-01-23T11:02:41.34+0800 [STG/0] OUT              File "django/__init__.py", line 1, in <module>
   2018-01-23T11:02:41.34+0800 [STG/0] OUT                from django.utils.version import get_version
   2018-01-23T11:02:41.34+0800 [STG/0] OUT              File "django/utils/version.py", line 61, in <module>
   2018-01-23T11:02:41.34+0800 [STG/0] OUT                @functools.lru_cache()
   2018-01-23T11:02:41.34+0800 [STG/0] OUT            AttributeError: 'module' object has no attribute 'lru_cache'
   2018-01-23T11:02:41.34+0800 [STG/0] OUT
   2018-01-23T11:02:41.34+0800 [STG/0] OUT            ----------------------------------------
   2018-01-23T11:02:42.10+0800 [STG/0] ERR        Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-IM9rTs/django/
   2018-01-23T11:02:42.32+0800 [STG/0] OUT        **ERROR** Could not install pip packages: Couldn't run pip: exit status 1
   2018-01-23T11:02:42.33+0800 [STG/0] ERR Failed to compile droplet: Failed to run all supply scripts: exit status 14
   2018-01-23T11:02:42.34+0800 [STG/0] OUT Exit status 223
   2018-01-23T11:02:42.35+0800 [STG/0] OUT Stopping instance 0531cf66-6347-41ff-bd02-7cc510be113b
   2018-01-23T11:02:42.35+0800 [STG/0] OUT Destroying container
   2018-01-23T11:02:46.30+0800 [STG/0] OUT Successfully destroyed container

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by sclevine** [comment]
Looks like you're trying to install a Python 3-only version of Django with Python 2.7:
https://stackoverflow.com/questions/42196124/there-are-errors-when-i-install-django-by-git

**Comment by sclevine** [comment]
Closing due to inactivity.
